/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-04-02 07:48:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".join_row{\r\n");
      out.write("   width:700px;\r\n");
      out.write("   margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"wrapper row3 join_row\">\r\n");
      out.write("    <h2 class=\"sectiontitle\">회원가입</h2>\r\n");
      out.write("    <form method=post action=\"../member/join_ok.do\" name=\"join_frm\">\r\n");
      out.write("    <table class=\"table\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">ID</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"id\" id=\"id\" class=\"input-sm\" style=\"float:left\" readonly>&nbsp;\r\n");
      out.write("          <input type=\"button\" value=\"중복체크\" class=\"btn btn-sm btn-primary\" style=\"float:left\" id=\"checkBtn\">\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">비밀번호</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=password name=\"pwd\" id=\"pwd\" class=\"input-sm\" style=\"float:left\">\r\n");
      out.write("          &nbsp;\r\n");
      out.write("          <input type=password name=\"pwd\" id=\"pwd1\" class=\"input-sm\" style=\"float:left\" placeholder=\"재입력\">\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">이름</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"name\" id=\"name\" class=\"input-sm\">\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">성별</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <ul class=\"inline\">\r\n");
      out.write("            <li><input type=radio name=\"sex\" class=\"input-sm\" checked value=\"남자\">남자</li>\r\n");
      out.write("            <li><input type=radio name=\"sex\" class=\"input-sm\" value=\"여자\">여자</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">생년월일</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=date size=\"20\" name=\"birthday\">\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">이메일</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"email\" id=\"email\" class=\"input-sm\" size=45>\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">우편번호</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"post\" id=\"post\" class=\"input-sm\" size=10 readonly style=\"float:left\">\r\n");
      out.write("          <input type=button value=\"우편번호검색\" class=\"btn btn-sm btn-danger\" id=\"postBtn\" style=\"float:left\">\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">주소</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"addr1\" id=\"addr1\" class=\"input-sm\" size=45 readonly>\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">상세주소</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"addr2\" id=\"addr2\" class=\"input-sm\" size=45>\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">전화번호</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <input type=text name=\"tel1\" id=\"tel1\" class=\"input-sm\" size=5 readonly value=\"010\"\r\n");
      out.write("          style=\"float: left\">\r\n");
      out.write("          <input type=text name=\"tel2\" id=\"tel2\" class=\"input-sm\" size=10 style=\"float: left\">\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th width=20% class=\"text-right\">소개</th>\r\n");
      out.write("        <td width=80%>\r\n");
      out.write("          <textarea rows=\"7\" cols=\"50\" name=\"content\"></textarea>\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("      \r\n");
      out.write("      <tr>\r\n");
      out.write("        \r\n");
      out.write("        <td colspan=\"2\" class=\"text-center\">\r\n");
      out.write("          <input type=submit value=\"회원가입\" class=\"btn btn-sm btn-success\">\r\n");
      out.write("          <input type=button value=\"취소\" class=\"btn btn-sm btn-warning\"\r\n");
      out.write("           onclick=\"javascript:history.back()\"\r\n");
      out.write("          >\r\n");
      out.write("        </td> \r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
